version: '3'
services:
  jdownloader-2:
    image: jlesage/jdownloader-2
    ports:
      - "5800:5800"
    volumes:
      - ./jdownloader-2:/config
      - /mnt/routershare/downloads:/output
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
