version: '3'

networks:
  frontend:
    external: true
  backend:

services:

  app:
    image: nextcloud
    restart: always
    volumes:
      - ./nextcloud:/var/www/html
    environment:
      MYSQL_PASSWORD: 'XXX'
      MYSQL_DATABASE: 'nextcloud' 
      MYSQL_USER: 'nextcloud'
      MYSQL_HOST: 'nextcloud-db'
      TZ: 'Europe/Paris'
    networks:
      - frontend
      - backend
    links:
      - db
    external_links:
      - npm-web
    container_name: nextcloud-app

  db:
    image: 'linuxserver/mariadb:arm32v7-latest'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'XXX'
      MYSQL_DATABASE: 'nextcloud' 
      MYSQL_USER: 'nextcloud'
      MYSQL_PASSWORD: 'XXX'
      TZ: 'Europe/Paris'
    volumes:
      - ./mariadb/mysql:/var/lib/mysql
    networks:
      - backend
    container_name: nextcloud-db

