version: '3'

networks:
  frontend:
    external: true
  backend:

services:

  app:
    image: nextcloud:27 #specifying the version is mandatory as Nextcloud won't allow upgrade that skip a major release
    restart: always
    volumes:
      - ./data/nextcloud:/var/www/html
      - ./data/apps:/var/www/html/custom_apps
      - ./data/config:/var/www/html/config
      - ./data/data:/var/www/html/data
    environment:
      MYSQL_PASSWORD: 'CHANGE_ME'
      MYSQL_DATABASE: 'nextcloud' 
      MYSQL_USER: 'nextcloud'
      MYSQL_HOST: 'nextcloud-db'
      TZ: 'Europe/Paris'
    networks:
      - frontend
      - backend
    links:
      - db
    external_links:
      - npm-web
    container_name: nextcloud-app

  db:
    image: 'mariadb:latest'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'CHANGE_ME'
      MYSQL_DATABASE: 'nextcloud' 
      MYSQL_USER: 'nextcloud'
      MYSQL_PASSWORD: 'CHANGE_ME'
      TZ: 'Europe/Paris'
    volumes:
      - ./mariadb/mysql:/var/lib/mysql
    networks:
      - backend
    container_name: nextcloud-db

