version: '3'

services:
  app:
    container_name: homeassistant-app
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./ha-config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    environment:
      - DISABLE_JEMALLOC:true

  deconz:
    image: deconzcommunity/deconz
    container_name: deconz
    restart: always
    ports:
      - 90:80
      - 453:443
    volumes:
      - /opt/deconz:/opt/deCONZ
    devices:
      - /dev/ttyACM0
    environment:
      - DECONZ_WEB_PORT=80
      - DECONZ_WS_PORT=443
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0
 
