
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate
http:
  use_x_forwarded_for: true
  trusted_proxies: # will prevent from being blocked when trying to access through the reverse proxy. Change it !
    - 172.17.0.0/16
    - 192.168.128.1

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

api:

alexa:
  smart_home:
