version: "3"

networks:
  frontend: # this network will be used for any other docker that need an access through the reverse proxy
    external: false
    name: frontend
  backend:

services:
  app:
    image: 'jc21/nginx-proxy-manager:2.9.22'
    restart: always
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    environment:
      DB_SQLITE_FILE: "/data/npm.sqlite"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - frontend
      - backend
    container_name: npm-web

  db:
    image: 'linuxserver/mariadb:latest'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'CHANGE_ME'
      MYSQL_DATABASE: 'nginx-proxy-manager'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'CHANGE_ME'
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - backend
    container_name: npm-db
