version: '3.8'

networks:
  frontend:
    external: true
  backend:

services:
  homeassistant:
    container_name: z2m-ha
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./ha-config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    networks:
      - backend
      - frontend
    ports:
      - 8123:8123
    environment:
      - TZ=Europe/Paris
      - DISABLE_JEMALLOC:true

  mqtt:
    container_name: z2m-mosquitto
    image: eclipse-mosquitto:latest
    restart: unless-stopped
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - backend
    ports:
      - 1883:1883
      - 9001:9001
      
  zigbee2mqtt:
    container_name: z2m-zigbee2mqtt
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    volumes:
      - ./zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    ports:
       - 8080:8080
    networks:
      - backend
      - frontend
    environment:
      - TZ=Europe/Paris
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
